Missing functions
ebastien/ti_calcite pull request #1
Opened 2016-12-12 17:39 UTC by Muriel-Salvan

2016-12-15 05:52 UTC, ebastien requested changes

2016-12-15 05:52 UTC, ebastien commented on src/main/scala/com/amadeus/ti/calcite/SqlRoundFunction.scala
> +  OperandTypes.or(OperandTypes.NUMERIC_OR_INTERVAL,
The signature of the function should be restricted to only match what is actually supported by Impala: 

https://www.cloudera.com/documentation/enterprise/5-5-x/topics/impala_math_functions.html#math_functions

> round(double a), round(double a, int d), round(decimal a, int_type d)

As a first iteration we could limit ourselves to `round(double a)`.

2016-12-15 05:52 UTC, ebastien commented on src/main/scala/com/amadeus/ti/calcite/SqlRoundFunction.scala
> +// End SqlFloorFunction.java
Comment does not match with the name of the file.

2016-12-15 05:52 UTC, ebastien commented on src/main/scala/com/amadeus/ti/calcite/SqlRoundFunction.scala
> +/*
Not sure the ASF license applies here.

2017-01-04 12:30 UTC, Muriel-Salvan commented
PR corrected per review comments, and also added support for SUBSTRING and CONCAT.
Waiting for further review.

2017-01-04 13:51 UTC, ebastien approved these changes

2017-01-05 18:16 UTC, Muriel-Salvan commented
Can you merge it or give me write access to the repo?

2017-01-09 13:44 UTC, merged